name: Unit tests
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker build -f dev.Dockerfile -t gothdns .

      - name: Run docker image
        run: |
          docker run --name gothdns --rm -w /app -d -v $(pwd):/app gothdns

      - name: Run tests
        run: |
          docker exec gothdns sh -c "go test ./... -p 1 -race -v -coverpkg=./... -coverprofile=coverage.txt"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
