name: Unit tests
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker build -f dev.Dockerfile -t gauth-dns .

      - name: Run docker image
        run: |
          docker run --name gauth-dns --rm -w /app -d -v $(pwd):/app gauth-dns

      - name: Run tests
        run: |
          docker exec gauth-dns sh -c "go test ./... -p 1 -race -v -coverprofile=coverage.txt"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
